name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - "3.11"
          - "3.12"
          - "3.13"
          - "3.14"
          - "3.14t"
        redis-version:
          - "7.0"  # oldest version supported
          - "8.0"
          - "8.10"
    env:
      TERM: 'dumb'
      PYTHON_VERSION: ${{ matrix.python-version }}
      REDIS_VERSION: ${{ matrix.redis-version }}
    steps:
    - uses: actions/checkout@v6
      with:
        fetch-depth: 0  # Fetch all history for all branches

    - name: Install uv and Python
      uses: astral-sh/setup-uv@v7
      with:
        enable-cache: true
        python-version: ${{ matrix.python-version }}

    - name: Setup uv venv
      run: uv sync --locked --all-extras --dev

    - name: Lint with ruff
      run: uv run ruff check streaq/ tests/ example.py

    - name: Type check with zuban (default)
      run: uv run zuban check streaq/ tests/ example.py

    - name: Type check with zuban (mypy)
      run: uv run zuban mypy streaq/ tests/ example.py

    - name: Test with pytest
      run: |
        docker compose run --rm -e COVERAGE_EXCLUDE=${{ matrix.redis-version == '8.10' && 'xreadgroup-no-max-count' || 'xreadgroup-max-count' }} tests uv run --locked --all-extras --dev pytest -n auto --cov=streaq tests/
